In [31]:
import numpy as np
x= np.array([1,2,3])
print(x)

[1 2 3]


In [2]:
x= [1,2]
arr = np.array(x)
print(arr)

[1 2]


In [3]:
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
np.full((2,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [6]:
arr1 = np.arange(2,102,2)
print(arr1)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [16]:
arr = np.zeros(10,dtype=int)
print(arr)
arr1 = np.ones(10,dtype=int)*5
print(arr1)

[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


In [8]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.01962197 0.66520474 0.24420559]
  [0.50165867 0.5350017  0.35750323]
  [0.0592003  0.59462668 0.10213877]]

 [[0.85062569 0.93330847 0.60707525]
  [0.73952313 0.22739213 0.7480373 ]
  [0.68331073 0.40663794 0.38370061]]

 [[0.61583895 0.05243793 0.55252426]
  [0.61089548 0.88839782 0.85411936]
  [0.95569049 0.59847688 0.41666144]]]


In [10]:
x = np.arange(10,22).reshape(3,4)
print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [10]:
np.arange(5,35,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [38]:
import random
np.random.seed(0)
np.random.uniform(0,1,6).reshape(3,2)


array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [12]:
rep=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(rep==1)[0][5-1]

8

In [17]:
x = np.arange(1, 10)
print("Original array:",x)
print("After splitting:")
print(np.split(x, [4, 6]))

Original array: [1 2 3 4 5 6 7 8 9]
After splitting:
[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


In [43]:
x = [[ 0., 1., 2., 3.], [ 4., 5., 6., 7.], [ 8., 9., 10., 11.], [ 12., 13., 14., 15.]]
x=np.array(x)
array1=np.split(x,2)
print(array1)

[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]


In [15]:
x = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(x)
print(x[0:2,1:])
print(x[1,0])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[10 15]
 [25 30]]
20


In [16]:
x = np.array([[ 1,2,3],[ 4,5,6]])
y = np.array([[ 1,2,3],[ 4,5,6]])
print(np.concatenate((x,y+6),axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [40]:
import random
random.seed(100)
array= np.random.randint(1,11,(5,3))
print("Array:\n",array)
print("Min/max: ",array.min(axis=1)/array.max(axis=1))

Array:
 [[5 4 1]
 [4 6 1]
 [3 4 9]
 [2 4 4]
 [4 8 1]]
Min/max:  [0.2        0.16666667 0.33333333 0.5        0.125     ]


In [18]:
arr1=np.arange(0,3)
arr2=np.arange(3,7)
arr3=np.arange(7,10)
np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a=np.array([2, 6, 1, 9, 10, 3, 27])
for x in a:
    if((x >= 5) & (x <= 10)):
        print(x)

6
9
10


In [20]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b= np.array([7,2,10,2,7,4,9,4,9,8])
np.arange(len(a))[a==b]

array([1, 3, 5, 7])

In [21]:
a= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[np.where(a%2==1)] =-1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
a= np.arange(0,10).reshape((2,5))
print(a)
b=np.ones((2,5),dtype=int)
print(b)
out_array=np.hstack((a,b))
print(out_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [22]:
x = np.array([ 3,  6,  9,  25, 10,  8])
print(x[1:])

[ 6  9 25 10  8]


In [23]:
print(x[:-1])

[ 3  6  9 25 10]


In [35]:
print(x[::2])

[ 3  9 10]


In [36]:
print(x[1:])

[ 6  9 25 10  8]


In [37]:
print(x[::-1])

[ 8 10 25  9  6  3]


In [25]:
x = np.arange(0,32).reshape(8,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [39]:
x[0][2] = "0";
print(x)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [40]:
print(x[:,1])

[ 1  5  9 13 17 21 25 29]


In [26]:
print(x[2:5,1:4])

[[ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [43]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [45]:
a_2d=np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d=np.array( [1,2,3])
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [46]:
x = np.random.randn(1000)
print("Average of the array elements:")
mean = round(x.mean(),5)
print(mean)
print("Standard deviation of the array elements:")
std = round(x.std(),5)
print(std)
print("Variance of the array elements:")
var = round(x.var(),5)
print(var)

Average of the array elements:
-0.011421884637893434
Standard deviation of the array elements:
0.9687
Variance of the array elements:
0.93838


In [47]:
a = np.arange(1,7)
b = np.arange(1,7).reshape(6,1)
a*b

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [41]:
import numpy as np
a=np.ones((6,6))
b=np.array([1,2,3,4,5,6])
for i in range(6):
    for j in range(6):
        a[i,j]=a[i,j]*b[i]*b[j]
print(a)

[[ 1.  2.  3.  4.  5.  6.]
 [ 2.  4.  6.  8. 10. 12.]
 [ 3.  6.  9. 12. 15. 18.]
 [ 4.  8. 12. 16. 20. 24.]
 [ 5. 10. 15. 20. 25. 30.]
 [ 6. 12. 18. 24. 30. 36.]]


In [8]:
import random
random.seed(100)
x = np.random.rand(10,3)
print(x)

[[0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329]
 [0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033]
 [0.56843395 0.0187898  0.6176355 ]]


In [9]:
y = np.mean(x,axis=0)
print(y)

[0.49494508 0.59155974 0.57871622]


In [10]:
z = x-y
print(z)

[[-0.05735787  0.30021326  0.38494654]
 [-0.11150356  0.2001653  -0.0498213 ]
 [ 0.07309948  0.3340369  -0.50768016]
 [-0.40781578 -0.57134134  0.25390363]
 [ 0.28321167  0.27845241  0.39990213]
 [ 0.30421348 -0.13008038  0.20181296]
 [-0.37667066  0.04836128 -0.43536293]
 [ 0.44972384 -0.06971142 -0.16405428]
 [-0.23038947  0.18267395 -0.12256588]
 [ 0.07348887 -0.57276994  0.03891928]]


In [11]:
print(np.mean(z))

1.4802973661668754e-17
